app/
│
├───main.cpp
├───torneos.db
│
├───data/
│   ├───stackHistoric.h ✅
│   ├───stackHistoric.cpp ✅
│   └───queue.h
│
├───models/ # Estructuras
│   ├───tournaments.h ✅
│   ├───teams.h ✅
│   ├───players.h ✅
│   ├───matches.h ✅
│   ├───petitions.h ✅
│   └───historic.h ✅
│
├───logics/
│   ├───logTournament.h ✅
│   ├───logTournament.cpp ✅
│   ├───logTeam.h ✅
│   ├───logTeam.cpp ✅
│   ├───logPlayer.h ✅
│   ├───logPlayer.cpp ✅
│   ├───logMatch.h ✅
│   ├───logMatch.cpp ✅
│   ├───logPetition.h ✅
│   ├───logPetition.cpp ✅
│   ├───logHistoric.h ✅
│   ├───logHistoric.cpp ✅
│   ├───logGame.h   # Falta las funciones de grupos, eliminatorias y tablaPuntaje
│   └───logGame.cpp # Falta las funciones de grupos, eliminatorias y tablaPuntaje
│
├───dataAccess/
│   ├───connection.h ✅
│   └───connection.cpp ✅
│
├───views/
│   ├───
│   └───