#pragma once

// ==========================
// SUCCESS (2000 - 2999)
// ==========================

// --- GENERAL ---
#define CODE_SUCCESS 2000

// --- PLAYER ---
#define CODE_PLAYER_CREATED 2001
#define CODE_PLAYER_UPDATED 2002
#define CODE_PLAYER_DELETED 2003
#define CODE_PLAYER_LISTED 2004

// --- TEAM ---
#define CODE_TEAM_CREATED 2101
#define CODE_TEAM_UPDATED 2102
#define CODE_TEAM_DELETED 2103
#define CODE_TEAM_GENERATE 2103
#define CODE_TEAM_LISTED 2104

// --- PETITION ---
#define CODE_PETITION_CREATED 2201
#define CODE_PETITION_ATTENDED 2202
#define CODE_PETITION_CANCELLED 2203
#define CODE_PETITION_LISTED 2204
#define CODE_PETITION_UPDATED 2205
#define CODE_PETITION_DELETED 2206

// --- TOURNAMENT ---
#define CODE_TOURNAMENT_CREATED 2301
#define CODE_TOURNAMENT_LISTED 2302
#define CODE_TOURNAMENT_UPDATED 2303
#define CODE_TOURNAMENT_DELETED 2304

// --- MATCH ---
#define CODE_MATCH_CREATED 2401
#define CODE_MATCH_LISTED 2402
#define CODE_MATCH_UPDATED 2403
#define CODE_MATCH_DELETED 2404

// --- HISTORIC ---
#define CODE_HISTORIC_CREATED 2501
#define CODE_HISTORIC_LISTED 2502
#define CODE_HISTORIC_DELETED 2503

// ==========================
// ERRORS (4000 - 4999)
// ==========================

// --- GENERAL ---
#define CODE_ERROR 4000
#define CODE_EXCEPTION 4001
#define CODE_ERROR_DB 4002
#define CODE_ERROR_DB_CONNECTION 4003
#define CODE_ERROR_DB_INIT 4003


// --- PLAYER ---
#define CODE_PLAYER_NOT_FOUND 4101
#define CODE_PLAYER_ALREADY_EXISTS 4102
#define CODE_PLAYER_INVALID_DATA 4103
#define CODE_PLAYER_DUPLICATE 4103

// --- TEAM ---
#define CODE_TEAM_NOT_FOUND 4201
#define CODE_TEAM_ALREADY_EXISTS 4202
#define CODE_TEAM_FULL 4203
#define CODE_TEAM_INVALID_DATA 4204
#define CODE_TEAM_DUPLICATE 4204

// --- PETITION ---
#define CODE_PETITION_NOT_FOUND 4301
#define CODE_PETITION_INVALID_TYPE 4302
#define CODE_PETITION_ALREADY_ATTENDED 4303
#define CODE_PETITION_INVALID_STATUS 4304
#define CODE_PETITION_INVALID_DATA 4305

// --- HISTORIC ---
#define CODE_HISTORIC_EMPTY 4401
#define CODE_UNDO_NOT_AVAILABLE 4402
#define CODE_HISTORIC_JSON_ERROR 4403
#define CODE_HISTORIC_INVALID_DATA 4404
#define CODE_HISTORIC_NOT_FOUND 4405

// --- TOURNAMENT ---
#define CODE_TOURNAMENT_NOT_FOUND 4501
#define CODE_TOURNAMENT_INVALID_DATA 4501
#define CODE_TOURNAMENT_DUPLICATE 4501

// --- TOURNAMENT --- 
#define CODE_MATCH_INVALID_DATA 4601

// --- MATCH ---
#define CODE_MATCH_NOT_FOUND 4601
